# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('catalogue', '0009_slugfield_noop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BauerProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.Product')),
                ('extra_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-date_created'],
                'abstract': False,
                'verbose_name': 'Product',
            },
            bases=('catalogue.product',),
        ),
        migrations.CreateModel(
            name='InstructionProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.Product')),
                ('blank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_blank', to='catalogue.Product')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-date_created'],
                'abstract': False,
                'verbose_name': 'Product',
            },
            bases=('catalogue.product',),
        ),
    ]
