# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_update_email_length'),
        ('reviews', '0003_auto_20160802_1358'),
        ('offer', '0003_auto_20161120_1707'),
        ('analytics', '0002_auto_20140827_1705'),
        ('partner', '0004_auto_20160107_1755'),
        ('wishlists', '0002_auto_20160111_1108'),
        ('basket', '0007_slugfield_noop'),
        ('customer', '0003_update_email_length'),
        ('promotions', '0002_auto_20150604_1450'),
        ('catalogue', '0010_bauerproduct_instructionproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstructionProduct',
            new_name='InstructionsWithBlankProduct',
        ),
        migrations.RemoveField(
            model_name='bauerproduct',
            name='extra_content',
        ),
        migrations.RemoveField(
            model_name='bauerproduct',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='BauerProduct',
        ),
    ]
