# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20171221_1911'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='instructionsproduct',
            managers=[
                ('browsable', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
