# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20190929_1421'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='instructionsproduct',
            managers=[
            ],
        ),
    ]
