# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=50, null=True, verbose_name='Access Token')),
                ('application_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Application ID')),
                ('location_desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location Description')),
                ('location_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location ID')),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
