# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_squaresettings_location_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squaresettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='SquareSettings',
        ),
    ]
