# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:23
from __future__ import unicode_literals
from django.db import migrations
from django.apps import apps as global_apps

def migrate_data(apps, schema_editor):
    
    try:
       unfinished = apps.get_model('products', 'UnfinishedBlank') 
       finished = apps.get_model('products', 'FinishedCarving') 
       instructions = apps.get_model('products', 'Instructions') 

    except LookupError:
        return



class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop)
    ]
