# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:23
from __future__ import unicode_literals
from django.db import migrations
from django.apps import apps as global_apps
from duxdekes.util import dataimport


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(dataimport.import_data, migrations.RunPython.noop)
    ]
