# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('duxdekes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SquareSettings',
            fields=[
                ('sitesettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='duxdekes.SiteSettings')),
                ('access_token', models.CharField(blank=True, max_length=50, null=True, verbose_name='Access Token')),
                ('application_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Application ID')),
                ('location_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location ID')),
            ],
            bases=('duxdekes.sitesettings',),
        ),
        migrations.CreateModel(
            name='UPSSettings',
            fields=[
                ('sitesettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='duxdekes.SiteSettings')),
                ('user', models.CharField(blank=True, max_length=99, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=99, null=True, verbose_name='Account Password')),
                ('license', models.CharField(blank=True, max_length=50, null=True, verbose_name='License Number')),
                ('testing', models.BooleanField(default=True, verbose_name='Testing')),
            ],
            bases=('duxdekes.sitesettings',),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
