# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duxdekes', '0003_auto_20171120_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squaresettings',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Access Token'),
        ),
    ]
