# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_update_email_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Final shipping charge'),
        ),
    ]
