# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_final_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_basket_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Final basket total'),
        ),
    ]
