# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('products', '0001_initial'), ('products', '0002_auto_20170113_1418'), ('products', '0003_auto_20170130_1243'), ('products', '0004_auto_20170130_1331'), ('products', '0005_auto_20170131_1144'), ('products', '0006_auto_20170131_1229'), ('products', '0007_product_updated')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('product_id', models.CharField(max_length=30, unique=True, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hide product?')),
            ],
            options={
                'default_related_name': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('u', 'Unfinished Blanks'), ('f', 'Finished Decoys'), ('i', 'Instructions'), ('m', 'Materials')], default='u', max_length=1, verbose_name='Type')),
                ('description', models.CharField(max_length=300, verbose_name='Name')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hide category?')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Extra category information')),
                ('slug', models.SlugField()),
                ('template', models.CharField(blank=True, max_length=300, null=True, verbose_name='Custom template')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID'),
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(choices=[('u', 'Unfinished Blanks'), ('f', 'Finished Decoys'), ('i', 'Instructions'), ('m', 'Materials'), (None, 'Unset')], default='u', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
