# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('product_id', models.CharField(max_length=30, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hide product?')),
            ],
            options={
                'default_related_name': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Name')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hide category?')),
                ('explanation', models.TextField(blank=True, verbose_name='Extra category information')),
            ],
        ),
        migrations.CreateModel(
            name='Decoy',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('productcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.ProductCategory')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.ProductCategory')),
            ],
            bases=('products.productcategory',),
        ),
        migrations.CreateModel(
            name='FinishedDecoy',
            fields=[
                ('decoy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Decoy')),
            ],
            bases=('products.decoy',),
        ),
        migrations.CreateModel(
            name='UnfinishedDecoy',
            fields=[
                ('decoy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Decoy')),
                ('materials', models.CharField(choices=[('OAK', 'Oak'), ('PINE', 'Pine')], max_length=10, verbose_name='Material')),
            ],
            bases=('products.decoy',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductType'),
        ),
    ]
