# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_squashed_0007_product_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Name')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('width', models.IntegerField(verbose_name='Width')),
                ('image', models.ImageField(height_field=models.IntegerField(verbose_name='Height'), upload_to='products/', verbose_name='Picture', width_field=models.IntegerField(verbose_name='Width'))),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='Pictures', to='products.Picture'),
        ),
    ]
