# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('product_id', models.CharField(max_length=30, unique=True, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hide product?')),
            ],
            options={
                'default_related_name': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('u', 'Unfinished Decoys'), ('f', 'Finished Decoys'), ('i', 'Instructions'), ('m', 'Materials')], default='u', max_length=1, verbose_name='Type')),
                ('description', models.CharField(max_length=300, verbose_name='Name')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hide category?')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Extra category information')),
                ('slug', models.SlugField()),
                ('template', models.CharField(blank=True, max_length=300, null=True, verbose_name='Custom template')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductCategory'),
        ),
    ]
