# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_squashed_0007_product_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='products',
            field=models.ManyToManyField(related_name='Products', to='products.Product'),
        ),
    ]
