# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170130_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID'),
        ),
    ]
