# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170215_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='height',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='width',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Picture'),
        ),
    ]
