# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170215_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedDecoy',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Instructions only price')),
                ('blank_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price with Blank')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='UnfinishedDecoy',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('pine_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price of Pine')),
                ('feet_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Optional Feet Fee')),
                ('tupelo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price of Tupelo')),
            ],
            bases=('products.product',),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.AddField(
            model_name='instructions',
            name='matching_blank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UnfinishedDecoy'),
        ),
    ]
