# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170130_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedDecoy',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='UnfinishedBlank',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(choices=[('u', 'Unfinished Blanks'), ('f', 'Finished Decoys'), ('i', 'Instructions'), ('m', 'Materials')], default='u', max_length=1, verbose_name='Type'),
        ),
    ]
