# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170131_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finisheddecoy',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='material',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='unfinishedblank',
            name='product_ptr',
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(choices=[('u', 'Unfinished Blanks'), ('f', 'Finished Decoys'), ('i', 'Instructions'), ('m', 'Materials'), (None, 'Unset')], default='u', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.DeleteModel(
            name='FinishedDecoy',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='UnfinishedBlank',
        ),
    ]
