# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:39
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170216_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructions',
            options={'verbose_name_plural': 'Instructions'},
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='products/', verbose_name='Picture'),
        ),
    ]
