# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170221_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finisheddecoy',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='matching_blank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.UnfinishedDecoy'),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Instructions only price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden'),
        ),
    ]
