# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170222_1422'),
    ]

    operations = [
        migrations.RenameModel('UnfinishedDecoy', 'UnfinishedBlank'),
        migrations.RenameModel('FinishedDecoy', 'FinishedCarving'),
    ]
